apiVersion: v1
kind: Secret
metadata:
  name: google-credential
type: Opaque
data:
  credential_json: ewogICJjbGllbnRfaWQiOiAiNzY0MDg2MDUxODUwLTZxcjRwNmdwaTZobjUwNnB0OGVqdXE4M2RpMzQxaHVyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwKICAiY2xpZW50X3NlY3JldCI6ICJkLUZMOTVRMTlxN01RbUZwZDdoSEQwVHkiLAogICJxdW90YV9wcm9qZWN0X2lkIjogInN0YXJyeS1zdW1tZXItNDAyNTAyIiwKICAicmVmcmVzaF90b2tlbiI6ICIxLy8wZTdUMzNFVEo0MUlEQ2dZSUFSQUFHQTRTTndGLUw5SXJpYXBBTmxBc3BFaEpFdUZONFhJbmJtTmNLUWlaamFNMjRzM21zeXZFTTQ5cHdLLU04US1nalJEZm56cTFXaEZaejRzIiwKICAidHlwZSI6ICJhdXRob3JpemVkX3VzZXIiCn0=