apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
  namespace: ingress-nginx
  labels:
    app: identity-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identityapi
          image: 281901/identity.api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: identity-port
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:443;http://+:80"
            - name: ConnectionStrings__IdentityDB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: connection_string
            - name: Google__ClientId
              valueFrom:
                secretKeyRef:
                  name: identity-api-secret
                  key: client_id
            # - name: KeyVault__ClientId
            #   valueFrom:
            #     secretKeyRef:
            #       name: keyvault-secret
            #       key: keyvault_client_id
            # - name: KeyVault__AzureKeyVaultURL
            #   valueFrom:
            #     secretKeyRef:
            #       name: keyvault-secret
            #       key: keyvault_url
            # - name: KeyVault__ClientSecret
            #   valueFrom:
            #     secretKeyRef:
            #       name: keyvault-secret
            #       key: keyvault_client_secret
            # - name: KeyVault__AzureClientTenantId
            #   valueFrom:
            #     secretKeyRef:
            #       name: keyvault-secret
            #       key: keyvault_client_tenant_id
            - name: Google__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: identity-api-secret
                  key: client_secret
            - name: IdentityUrl
              value: https://frontend.20.211.61.204.nip.io
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "200Mi"
              cpu: "0.3"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: identity-api-service
#   labels:
#     app: identity-api-service
# spec:
#   selector:
#     app: identity-api
#   ports:
#     - protocol: TCP
#       port: 5002
#       targetPort: 80
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
  namespace: ingress-nginx
  labels:
    app: identity-api
spec:
  type: ClusterIP
  selector:
    app: identity-api
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-service-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    # nginx.ingress.kubernetes.io/rewrite-target: /identity/$2
spec:
  tls:
    - hosts:
        - frontend.20.211.61.204.nip.io # update IP address here
      secretName: app-web-cert
  rules:
    - host: frontend.20.211.61.204.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: identity-api-service
                port:
                  number: 80
