apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-config
data:
  ocelot.Production.json: |-
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/api/pricingPlan/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "GET"
          ],
          "UpstreamPathTemplate": "/payment/plan/{everything}",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "payment"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/pricingPlans",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "GET"
          ],
          "UpstreamPathTemplate": "/payment/planform",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "payment"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/subscription",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "POST"
          ],
          "UpstreamPathTemplate": "/payment/subscriptions",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "payment"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/create-payment-intent",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "POST"
          ],
          "UpstreamPathTemplate": "/payment/checkout",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "payment"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/create-portal-session",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "POST"
          ],
          "UpstreamPathTemplate":"/payment/customerportal",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "payment"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/subscription/success",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "GET"
          ],
          "UpstreamPathTemplate": "/subscription/success"
        },
        {
          "DownstreamPathTemplate": "/subscription/cancel",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "GET"
          ],
          "UpstreamPathTemplate": "/subscription/cancel"
        },
        {
          "DownstreamPathTemplate": "/stripe/webhook",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "payment-api-service",
              "Port": 80
            }
          ],
          "UpstreamHttpMethod": [
            "POST"
          ],
          "UpstreamPathTemplate": "/webhook"
        },
         {
          "DownstreamPathTemplate": "/api/tag/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "movie-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/tag/{everything}",
          "UpstreamHttpMethod": [
            "GET"
          ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "movies"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/movies/search?{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "movie-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/movies/search?{everything}",
          "UpstreamHttpMethod": [
            "GET"
          ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "movies"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/categories",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "movie-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/movies/categories",
          "UpstreamHttpMethod": [
            "GET"
          ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "movies"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/tags",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "movie-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/movies/tags",
          "UpstreamHttpMethod": [
            "GET"
          ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "movies"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/movies/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "movie-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/movies/{everything}",
          "UpstreamHttpMethod": [
            "GET"
          ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "movies"
            ]
          }
        },
        {
          "DownstreamPathTemplate": "/api/category/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "movie-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/category/{everything}",
          "UpstreamHttpMethod": [
            "GET"
          ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityApiKey",
            "AllowedScopes": [
              "movies"
            ]
          }
        }
      ]
    }
