name: "Deploy to AKS"

inputs:
  azure_credentials:
    description: "Credentials to connect to AKS"
    required: true
  cluster_name:
    description: "Name of AKS cluster"
    required: true
  resource_group:
    description: "Resource group of AKS cluster"
    required: true
  manifest_path:
    description: "Path to k8s manifest"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  image_name:
    description: "Name of image to deploy"
    required: true
  namespace:
    description: "Namespace to deploy to"
    required: true

runs:
  using: "composite"
  steps:
  # Logs in with your Azure credentials
  - name: Azure login
    uses: azure/login@v1.4.6
    with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Use kubelogin to configure your kubeconfig for Azure auth
  - name: Set up kubelogin for non-interactive login
    uses: azure/use-kubelogin@v1
    with:
        kubelogin-version: 'v0.0.25'

  # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
  - name: Get K8s context
    uses: azure/aks-set-context@v3
    with:
        resource-group: ${{ inputs.resource_group }}
        cluster-name: ${{ inputs.cluster_name }}
        admin: 'false'
        use-kubelogin: 'true'
  
  - name: Set branch name as env variable
    shell: bash
    run: |
      currentbranch=$(echo ${GITHUB_REF##*/})
      echo "running on $currentbranch"
      echo "BRANCH=$currentbranch" >> $GITHUB_ENV
  
  - name: Deploy microservice
    uses: azure/k8s-deploy@v4
    with:
      manifests: |
        ${{ inputs.manifest_path }}
      images: |
        ${{ inputs.registry_host }}/${{ inputs.image_name }}:${{ env.BRANCH }}
      pull-images: true
      namespace: ${{ inputs.namespace }}