version: '3.4'

services:
  moviedb:
    image: mongo

  crawlerdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:management
  
  # identitydb:
  #   image: postgres

  ocelotapigw:
    image:
      ${REGISTRY:-simpleNetflix}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    # uncomment the following lines to run the ocelotapigw locally
    #  ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.SimpleNetflix/OcelotApiGw/Dockerfile

  # identity.api:
  #   image:
  #    ${REGISTRY:-simpleNetflix}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
  #   # uncomment the following lines to run the identity.api locally
  #   #  ${DOCKER_REGISTRY-}identityapi
  #   build:
  #     context: .
  #     dockerfile: src/Services/Identity/Identity.API/Dockerfile
  #   depends_on:
  #     - identitydb

  movie.api:
    image:
      ${REGISTRY:-simpleNetflix}/movie.api:${PLATFORM:-linux}-${TAG:-latest}
    # uncomment the following lines to run the movie.api locally
    #  ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: src/Services/Movie/Movie.API/Dockerfile
    depends_on:
      - moviedb


  crawldata:
    image: ${REGISTRY:-simpleNetflix}/crawldata:${PLATFORM:-linux}-${TAG:-latest}
    # ${DOCKER_REGISTRY-}crawldata
    build:
      context: .
      dockerfile: src/Services/Crawler/CrawlData/Dockerfile
    depends_on:
     - crawlerdb

