version: '3.4'

services:
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.SimpleNetflix/OcelotApiGw/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile


  movie.api:
    image: ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: src/Services/Movie/Movie.API/Dockerfile

