version: '3.4'

services:
  moviedb:
    image: mongo
  
  identitydb:
    image: postgres

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.SimpleNetflix/OcelotApiGw/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - identitydb

  movie.api:
    image: ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: src/Services/Movie/Movie.API/Dockerfile
    depends_on:
      - moviedb

