version: '3.4'

services:
  moviedb:
    container_name: moviedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - simplenetflix-moviedb:/data/db

  identitydb:
    container_name: identitydb
    environment:
      - POSTGRES_USER=meofadmin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=IdentityDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - simplenetflix-identitydb:/var/lib/postgresql/data

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
    ports:
      - "5001:80"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__IdentityDB=User ID=meofadmin;Password=123456;Server=identitydb;Port=5432;Database=IdentityDB
      - MovieApiClient=http://docker.for.mac.localhost:8000
      - USER_SECRETS_ID=9201287f-9e32-478f-903b-c2bee2bcb15a
    ports:
      - "5002:80"
    volumes:
      - ~/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - ~/.aspnet/https:/root/.aspnet/https:ro

  movie.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - DatabaseSettings__ConnectionString=mongodb://moviedb:27017
      - DatabaseSettings__DatabaseName=sampleDB
      - DatabaseSettings__CollectionName=movies
    ports:
      - "8000:80"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro

volumes:
  simplenetflix-moviedb:
  simplenetflix-identitydb: