name: identity-api

on:
  workflow_dispatch:
  push:
    branches:
      - dev

    paths:
      - src/Services/Identity/**
      - .github/workflows/composite/build/action.yml
      - .github/workflows/identity-api.yml

  pull_request:
    branches:
      - dev

    paths:
      - src/Services/Identity/**
      - .github/workflows/identity-api.yml
env:
  SERVICE: identity-api
  IMAGE: identity.api

jobs:
  Linting_And_Build_Service:
    name: Lint, build and unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Print Current Directory
        run: |
          pwd  # This command prints the current working directory
          ls   # This command lists the contents of the current directory

      - name: Lint code
        working-directory: ./SimpleServer/src/Services/Identity/Identity.API
        run: dotnet format --verify-no-changes

      - name: Restore dependencies
        working-directory: ./SimpleServer/src/Services/Identity/Identity.API
        run: dotnet restore 

      - name: Build
        working-directory: ./SimpleServer/src/Services/Identity/Identity.API
        run: dotnet build 

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - uses: ./.github/workflows/composite/build
        with:
          service: ${{ env.SERVICE }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}  
             
