name: Deploy api gateway to k8s

on:
  workflow_dispatch:
  push:
    branches:
      - main

    paths:
      - .github/workflows/ocelotapigw-deploy.yml
      - .github/workflows/composite/deploy/action.yml
      - deploy/k8s/apigw.yaml
      - SimpleServer/src/ApiGateways/Web.Bff.SimpleNetflix/OcelotApiGw/**

env:
  NAMESPACE: ingress-nginx

jobs:
  deploy-to-k8s:
    permissions:
        actions: read
        # contents: read
        id-token: write
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - uses: ./.github/workflows/composite/deploy
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          manifest_path: |
            deploy/k8s/ocelot-config.yaml
            deploy/k8s/apigw.yaml
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          namespace: ${{ env.NAMESPACE }}
          image_name: ocelotapigw
          deployment_name: apigw-deployment 
          service_name: apigw-service
