# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Print Current Directory
      run: |
          pwd  # This command prints the current working directory
          ls   # This command lists the contents of the current directory
    - name: Lint code
      run: dotnet format SimpleServer/SimpleServer.csproj
    - name: Restore dependencies
      run: |
        cd SimpleServer
        dotnet restore
    - name: Build
      run: |
        cd SimpleServer
        dotnet build --no-restore
    - name: Test
      run: |
        cd SimpleServer
        dotnet test --no-build --verbosity normal
